apiVersion: apps/v1
kind: Deployment
metadata:
  name: akswebapp
  labels:
    app: akswebapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: akswebapp
  template:
    metadata:
      labels:
        app: akswebapp
    spec:
      containers:
      - name: akswebapp
        image: jpcontainerregisternew.azurecr.io/akswebapp:25
