apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: akswebapp
  name: akswebapp
  namespace: akswebapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: akswebapp
  template:
    metadata:
      labels:
        app: akswebapp
    spec:
      containers:
        image: jpcontainerregisternew.azurecr.io/akswebapp:18
        name: akswebapp
        envFrom:
        - configMapRef:
            name: env-config
