apiVersion: v1
kind: Service
metadata:
  labels:
    app: akswebapp
  name: akswebapp
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: akswebapp
  type: LoadBalancer
