apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
nameSuffix: -production
namespace: production
configMapGenerator:
- name: env-config
  literals:
  - ASPNETCORE_ENVIRONMENT=Production
