apiVersion: v1
kind: Pod
metadata:
  name: akswebapp-workload-identity
  labels:
    azure.workload.identity/use: "true"
spec:
  serviceAccountName: sa-akswebapp
  containers:
    - image: <CR>.azurecr.io/akswebapp:v1
      name: akswebapp-workload-identity
      env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"