name: Build and Push Container Image
on:
  workflow_dispatch:
  push:
    paths:
      - "AKSWebApp/**"
permissions:
  contents: write

jobs:
  build-and-push:
    runs-on: self-hosted
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
 
    - name: Login to ACR
run: echo ${{ secrets.ACR_PASSWORD }} | docker login myacr.azurecr.io -u ${{ secrets.ACR_USERNAME }} --password-stdin
