name: Build and Deploy to AKS
 
on:
  push:
    branches:
      - main
 
jobs:
  build-and-push:
    runs-on: self-hosted
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
 
    - name: Login to ACR
run: echo ${{ secrets.ACR_PASSWORD }} | docker login myacr.azurecr.io -u ${{ secrets.ACR_USERNAME }} --password-stdin
 
    - name: Build and Push Docker Image
      run: |
docker build -t myacr.azurecr.io/my-app:${{ github.sha }} .
docker push myacr.azurecr.io/my-app:${{ github.sha }}
