name: Build and Push Container Image
on:
  workflow_dispatch:
  push:
    paths:
      - "AKSWebApp/**"
permissions:
  contents: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
 
    - name: Login to ACR
      run: echo ${{ secrets.ACR_PASSWORD }} | docker login jpcontainerregisternew.azurecr.io -u ${{ secrets.ACR_USERNAME }} --password-stdin
    - name: Build and Push Docker Image
      run: |
          docker build -t jpcontainerregisternew.azurecr.io/akswebappnew:${{ github.sha }} ./AKSWebApp
          docker push jpcontainerregisternew.azurecr.io/akswebappnew:${{ github.sha }}
  Update-Kubernetes-Manifest:
    name: Update K8s Deployment Manifest
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v2

    - name: Update image name in manifest file
      uses: azure/powershell@v1
      with:
        inlineScript: |
          $WorkPath = $env:GITHUB_WORKSPACE
          Get-ChildItem -Path $WorkPath
          $DeploymentYAML = Join-Path -Path $WorkPath -ChildPath Manifests/deployment.yaml
          $line = Get-Content -Path $DeploymentYAML | Select-String image: | Select-Object -ExpandProperty Line
          $content = Get-Content $DeploymentYAML
          $content | ForEach-Object {$_ -replace $line,"        image: ${{ secrets.REGISTRY }}.azurecr.io/${{ secrets.REPOSITORY }}:${{ github.run_number }}"} | Set-Content -Path $DeploymentYAML
        azPSVersion: "latest"
    
    - name: Commit changes in manifest to repo
      run: | 
        git config user.name "GitHub Actions"
        git config user.email ""
        git add Manifests/deployment.yaml
        git commit -m "Update image version in K8s Deployment manifests file"
        git push origin
